project:
  type: website

website:
  title: Global Energy Trends
  navbar:
    right:
      - icon: github
        href: https://info523-s24.github.io/project-final-datadetectives/
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: Dashboard
        href: dashboard.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true

execute:
  freeze: auto
