project:
  type: website

website:
  title: "<img src='/images/data_detective_logo.png' alt='DD_Logo' style='width: 4em; height: 5em; border-radius: 30%;'> <b>Global Energy Trends</b>"
  navbar:
    right:
      - icon: github
        href: https://info523-s24.github.io/project-final-datadetectives/
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: Dashboard
        href: dashboard.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true

execute:
  freeze: auto
